name: Update Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: '*/6 * * * *' # `*/10 14-22 * * 1-5` runs at every 10th minute past every hour from 8:30 through 4:30 IST on every day-of-week from Monday through Friday
    # Note: 8:30 to 4:30 in IST is 14-22 for UTC

jobs:
  py_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.9' 
          cache: 'pip'
          # cache-dependency-path: '**/requirements.txt'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Execute Python script
        env:
          CRED: ${{ secrets.SERVICE_ACCOUNT_T }}
        run: python main_g.py
